Primer pull request
JLombar/HorariosAutomatricula pull request #1
Opened 2024-09-22 18:24 UTC by JLombar

Primer pull request

2024-09-23 16:06 UTC, JJ commented
Como pone en [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md):

> La lista de comprobación es imprescindible, porque te permite saber si lo que estás haciendo es efectivo o no y te ahorra trabajo tanto al estudiante (que no tendrá que revisar y enviar de nuevo) como al profesor. Pásala y compruébala.

Siguiendo [las instrucciones del guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#entrega-de-la-pr%C3%A1ctica), en este y en los siguientes objetivos, ahorraremos tiempo los dos.

2024-09-23 16:53 UTC, JLombar commented
@JJ Listo para revisión

2024-09-23 17:13 UTC, JJ requested changes
Si este fue el problema validado en el juego de rol, me temo que tendrás que intentarlo de nuevo; lo puedes hacer en la clase del jueves. Si no lo es, deberías volver al juego, que para eso se hizo, incluyendo la descripción del desarrollador que haya hecho con sus propias palabras. En todo caso, en [el guión del objetivo](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#tldr) dice (en el resumen):

> Pensar en un problema a resolver que tenga entidad suficiente para poder llevar a cabo su desarrollo durante el resto de la asignatura.

En ningún momento dice que describas qué aplicación quieres hacer, sino *un problema*

2024-09-23 17:13 UTC, JJ commented on README.md
> +El proyecto consistirá en un programa capaz de crearle a un estudiante un horario según las asignaturas que ha seleccionado en un matrícula con el menor número de coincidencias entre horarios posible
Describes una solución, no un problema. Como indica en [la página de errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md)

> Si de describe lo que el cliente quiere hacer sin decir por qué quiere hacerlo, no estás describiendo el problema, estás describiendo una solución. Es imposible de esa fomra solucionar el problema.

2024-09-23 17:30 UTC, JLombar commented on README.md
> +El proyecto consistirá en un programa capaz de crearle a un estudiante un horario según las asignaturas que ha seleccionado en un matrícula con el menor número de coincidencias entre horarios posible
@JJ Efectivamente, el problema es el validado en el juego de rol. Lo que le quería preguntar es ¿entonces con cambiar de la solución al problema e incluir la descripción del desarrollador estaría correcto? ¿o a lo que se refiere con volver a intentarlo es que no es un problema viable a parte del cambio que me ha comentado antes?

2024-09-23 18:30 UTC, JJ commented on README.md
> +El proyecto consistirá en un programa capaz de crearle a un estudiante un horario según las asignaturas que ha seleccionado en un matrícula con el menor número de coincidencias entre horarios posible
Lo que has escrito aquí no es un problema. Si está validado, me temo que sigue sin serlo. No me preguntes "si hago esto está bien o mal". Mira el guión y los errores que te he comentado, y vuélvelo a enviar con lo que consideres conveniente. Para eso están estos PRs, para que yo te evalúe lo que envíes (no las preguntas en las evaluaciones)

2024-09-23 18:55 UTC, JLombar commented
@JJ Listo para revisión

2024-09-23 19:02 UTC, JJ reviewed
A pesar de que en la lista de comprobación has dicho que:

>  ¿Se trata de un problema real del que se tenga conocimiento personal?
Sí, todos los años realizo la automatrícula de la UGR y tengo problemas con la misma así que es un problema real que he experimentado.

el *cliente* del problema dices que es *un programador*, no una persona que realiza la automatrícula. 

Si el problema es elegir asignaturas, ¿cuál es realmente el problema subyacente? ¿puede ser que sea extraer información de alguna fuente no estructurada?

2024-09-23 19:02 UTC, JJ commented on README.md
> +Soy un programador que trabaja para la UGR y se me ha encargado desarrollar un programa que asigne a cada alumno el horario que mejor le convenga teniendo en cuenta las asignaturas elegidas en su aut
¿Crees que lo que estás describiendo es un problema? Si lo es, ¿de quién es el problema? ¿Quién sería el cliente? ¿Qué problema o necesidad tendría el cliente?
Por otro lado, ¿normalmente a ti o a alguien que conozcas le encargan la confección del horario de informática?

2024-09-24 17:48 UTC, JLombar commented
@JJ Listo para revisión
He estado leyendo esta mañana sobre empatizar en el design thinking como me ha dicho y creo que esta vez estaría correcto, espero que así sea.
  
> Si el problema es elegir asignaturas, ¿Cuál es realmente el problema subyacente? ¿puede ser que sea extraer información de alguna fuente no estructurada?

Mi intención era enforcarlo a extraer información de una fuente no estructurada teniendo en cuenta las preferencias y necesidades del alumno que realiza la matrícula.

> ¿Crees que lo que estás describiendo es un problema? Si lo es, ¿de quién es el problema? ¿Quién sería el cliente? ¿Qué problema o necesidad tendría el cliente? Por otro lado, ¿normalmente a ti o a alguien que conozcas le encargan la confección del horario de informática?

No, espero que esté ya descrito como se pide. No, no conozco a nadie que le encarguen la confección.

2024-09-24 17:57 UTC, JJ requested changes
Eb la [explicación](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#explicaci%C3%B3n) del objetivo cero explica claramente en qué consiste la configuración. Borrarle una palabra a la licencia o añadir alguna cosa al .gitignore no contribuye lo más mínimo a que yo vea que has configurado correctamente tu conexión con GitHub siguiendo las instrucciones.
Por otro lado, en la lista de comprobación habrás marcado esto:

```
* [ ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
````

¿Hay algo enlazado, sea configuración o no, desde el README que te haya hecho marcarlo?

2024-09-24 17:57 UTC, JJ commented on README.md
> +#Descripción del problema
Markdown sólo admite una cabecera de primer nivel (#) y además tiene que estar separada por un espacio. Quizás quieras corregirlo antes de fusionarlo.

2024-09-24 17:57 UTC, JJ commented on README.md
> +Todos los años, una gran cantidad de alumnos de Ingeniería Informática de la UGR tienen problemas con su horario al comenzar el curso tras realizar la automatrícula, ya que el resultado suele incluir
¿Por qué lo que has dicho [aquí](https://github.com/JLombar/HorariosAutomatricula/pull/1#issuecomment-2371931766) no lo incluyes en la descripción? 
En [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) dice que una de las cosas que hay que incluir es información necesaria para que yo entienda que el problema tiene la entidad suficiente para poder continuar con la asignatura, y que entiendes como tienes que enfocarlo.

2024-09-24 17:58 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
>       Sí, todos los años realizo la automatrícula de la UGR y tengo problemas con la misma así que es un problema real que he experimentado.
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
>       Sí, se podría ampliar mucho y usar la nube podría ser una gran opción para darle mucha escalabilidad al sistema incluyendo muchas opciones.
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
>       Sí, requiere búsqueda de asignaturas según las opciones personalizadas del alumno evitando las colisiones en el horario y se podría completar incluyendo que se tenga en cuenta el número de alumnos en clase, o si el estudiante trabaja y gran cantidad de factores adicionales.
> 
>     * [x]  ¿Se ha incluido la configuración del repositorio y se ha enlazado desde el
>       `README`?
>       Sí, se encuentra enlazado
> 

¿El qué se encuentra enlazado donde?

>     * [x]  ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
>       a requerir que el usuario los introduzca?
>       Los datos existen en la web de la ETSIIT (en caso de sólo enfocar el problema a ingeniería informática que es la intención).

Esto ¿no crees que formaría parte de la descripción del problema?

2024-09-25 19:18 UTC, JLombar commented
@JJ Listo para revisión
No puedo enseñar como creo la llave ssh porque lo hice hace un par de días pero creo que se ve bien reflejado en el readme. He intentado añadir lo que me ha comentado de añadir el tema de los horarios existentes en la web de la etsiit usando el design thinking y creo que ha quedado correctamente. Por el último, el resto de cosas de la configuración y una pequeña demostración de que funciona han sido añadidas también. He cambiado también el markdown para que se vea bien.

2024-09-26 05:30 UTC, JJ commented
> 

Sí puedes enseñar como la has añadido al repo, ¿no?

2024-09-26 05:31 UTC, JJ commented
... que es lo que has hecho :-)

2024-09-26 05:31 UTC, JJ approved these changes
:+1:

2024-09-26 07:31 UTC, merged