[IV-24-25] Entregable Objetivo 5
JLombar/HorariosAutomatricula pull request #24
Opened 2024-12-04 17:57 UTC by JLombar

* [X] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están
considerando?

Sí, establecidos [aquí](https://github.com/JLombar/HorariosAutomatricula/blob/Objetivo-5/docs/imagen_docker.md)
* [X] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?

Sí, Bitnami proporciona versiones actualizadas de Python.
* [X] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?

Sí, es lastest
* [X] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una
vez, se va a usar cientos o miles de veces)

Sí
* [X] ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?

Sí, se han seguido las [recomendaciones](https://docs.docker.com/build/building/best-practices/)
* [X] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
   nuestro proyecto?

La imagen incluye algunas funcionalidades extra muy limitadas, siendo mejor opción que el resto de imágenes discutidas
* [X] ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?

Sí
* [X] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?

Sí
* [X] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?

En /app
* [X] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?

Sí, como ya se ha mencionado [aquí](https://github.com/JLombar/HorariosAutomatricula/blob/Objetivo-5/docs/imagen_docker.md)
* [X] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En
particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué
condiciones *no* deben darse?

Sí, que haya modficación en alguno de los archivos relacionados con la ejecución del programa, sin contar documentación
* [X] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?

Se tienen en cuenta todas las ramas, y los cambios en archivos ya explicados en el punto anterior
* [X] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el
directorio que monta, ya que no tiene derecho de escritura?

El comando CMD no escribe en el directorio
* [X] ¿Se ha abierto un shell en el contenedor una vez construida la imagen y
comprobado que los ficheros que se necesitan están todos incluidos, y que no hay
ficheros que no se necesiten?

Sí, los archivos que están en el [.dockerignore](https://github.com/JLombar/HorariosAutomatricula/blob/8ac83212eb3b6c49143c93557327b7fdcfc52b8f/.dockerignore) no están incluidos

2024-12-10 15:58 UTC, hossam1522 reviewed
Buenas, vas por buen camino, pero hay conceptos que debes pulir. ¡Ánimo!

2024-12-10 15:58 UTC, hossam1522 commented on .github/workflows/imagen_test.yml
> +        uses: docker/login-action@v2
¿Has validado que estés usando la versión más reciente?

2024-12-10 15:58 UTC, hossam1522 commented on .github/workflows/imagen_test.yml
> +        uses: actions/checkout@v3
¿Has validado que estés usando la versión más reciente?

2024-12-10 15:58 UTC, hossam1522 commented on .github/workflows/imagen_test.yml
> +        run: docker push ${{ secrets.DOCKER_USERNAME }}/horariosautomatricula:latest
No necesitas construir la imagen para subirla. Hay una job específica para esto que te ahorraría todos estos comandos (pista:docker/build-push-action). Tampoco necesitarías testear nada en teoría.

2024-12-10 15:58 UTC, hossam1522 commented on Dockerfile
> +COPY . /app
Creo que no has pillado del todo esto. Supuestamente para ejecutar, necesitas usar el comando:

```bash
docker run -u 1001 -t -v `pwd`:/app/test [nick-estudiante]/[nombre-del-repo]
```

donde `pwd`:/app/test indica que estás usando el directorio actual como volumen (si no sabes lo que son, te recomendaría que le echases un [vistazo](https://docs.docker.com/engine/storage/volumes/) ).

Resumiendo, a lo que voy, dentro de la imagen de docker solo necesitas tener la herramienta para hacer el test (en este caso, make) ya que los archivos del repositorio se lo estás pasando directamente con el volumen especificado al ejecutar el comando (es decir, el directorio actual).

Cualquier duda al respecto me comentas.

2024-12-10 15:58 UTC, hossam1522 commented on README.md
> +La documentación sobre la imagen de base elegida para Docker se encuentra [aquí](./docs/imagen_docker.md)
Ya que estamos, como el README principal es una especie de guía para la persona que llegue y no tenga nada de contexto sobre el tema, yo indicaría aquí cómo ejecutar los test usando el comando [especificado](http://jj.github.io/IV/documentos/proyecto/5.Docker#entrega-del-material-evaluable-en-este-objetivo), ya que si no, casi que no hay forma de enterarse de que dichos tests con la imagen docker existen.

2024-12-10 15:58 UTC, hossam1522 commented on .github/workflows/imagen_test.yml
> +      - '.github/workflows/imagen_test.yml'
Esto sobraría, siempre se va a ejecutar lo modifiques o no.

2024-12-10 15:58 UTC, hossam1522 commented on .github/workflows/imagen_test.yml
> +      - '**/*.py'
No tiene mucho sentido volver a subir la imagen siempre y cuando cambie un archivo que no tiene nada que ver realmente con la imagen. Más info aquí.

2024-12-10 17:56 UTC, JLombar commented on .github/workflows/imagen_test.yml
> +        run: docker push ${{ secrets.DOCKER_USERNAME }}/horariosautomatricula:latest
El último commit en el que termino de implementar esto es: [bd0c3e2](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/bd0c3e2bc0cb53c251886347b03a53edf921ecf8)

2024-12-10 17:59 UTC, JLombar commented on Dockerfile
> +COPY . /app
Efectivamente no lo había entendido para nada y me estaba replanteando el por qué estaba haciendo muchas cosas de las que estaba haciendo. Creo que ya lo entiendo correctamente y debería estar bien. Corregido en [c20a044](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/c20a044eac34506adbabfafa052e036715795a27) y en [26337da](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/26337da4f041590ec12a867051eeed38213516eb)

2024-12-10 17:59 UTC, JLombar commented on .github/workflows/imagen_test.yml
> +      - '.github/workflows/imagen_test.yml'
Eliminado

2024-12-10 18:03 UTC, JLombar commented on .github/workflows/imagen_test.yml
> +      - '**/*.py'
En este commit [df7203a](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/df7203a70addd34e1fad4cc8e82d70aee411b06f) elimino los paths innecesarios, de forma que sólo se ejecutará el workflow si cambian los archivos que afectan la construcción de la imagen, como el Dockerfile, Makefile, o el archivo de dependencias pyproject.toml

2024-12-13 10:29 UTC, JLombar commented
@hossam1522 Listo para revisión

2024-12-13 11:44 UTC, hossam1522 approved these changes
Por mi parte, apruebo el objetivo.

2024-12-13 11:54 UTC, JLombar commented
@JJ Listo para revisión

2024-12-13 14:41 UTC, JLombar commented
@JJ Listo para revisión

2024-12-13 14:41 UTC, JLombar commented
He estado mirando qué es necesario para la instalación de Python y he borrado un par que eran innecesarios como me ha , el resto, si no me equivoco, son necesarios

2024-12-13 19:26 UTC, JJ requested changes
Por favor, dale una pequeña vuelta más. Has explorado muchas versiones diferentes, y te lo has currado intentando construir Python desde 0; desgraciadamente, creo que te ha faltado examinar el resultado final y quitar lo que no haga falta. Y/o mirar la construcción en dos fases, que es lo que se suele usar en estos casos.

2024-12-13 19:26 UTC, JJ commented on Dockerfile
> +    shadow \
¿seguro que esto es necesario?

2024-12-13 19:26 UTC, JJ commented on Dockerfile
> +RUN curl -o /tmp/python.tar.xz https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz && \
si usas Alpine como base, ¿has probado a usar `wget` que viene instalado de serie?

2024-12-13 19:26 UTC, JJ commented on Dockerfile
> +    rm -rf /usr/src/python /tmp/python.tar.xz
OK, ya veo, te estás bajando los fuentes y compilándolos. En ese caso, ¿has considerado la construcción de la imagen en dos fases?

2024-12-13 19:26 UTC, JJ commented on Dockerfile
> +ENTRYPOINT [ "make", "test" ]
Si no has considerado la construcción en dos fases, ¿estás seguro que todo lo que has instalado arriba se tiene que quedar en la imagen?

2024-12-13 19:26 UTC, JJ commented on Makefile
>  	@curl -LsSf https://astral.sh/uv/install.sh | sh
`curl` no tiene que estar instalado por defecto siempre. Hay otros descargadores como `wget` que sí es más probable que estén.

2024-12-13 19:26 UTC, JJ commented on docs/imagen_docker.md
> +* Se tendrá en cuenta que la imagen pese poco, optimizando recursos al necesitar menos memoria y mayor velocidad de despliegue.
¿Cuanto pesa la imagen que obtienes?

2024-12-13 19:26 UTC, JJ commented on docs/imagen_docker.md
> +* No se piden funcionalidades extras al sólo ser usada para testear el proyecto
Pues tienes unas cuantas en la tuya...

2024-12-13 19:26 UTC, JJ commented on Dockerfile
> +RUN python3.12 --version
¿Otra vez con la versión? ¿Para qué quieres ejecutar `--version` si ya le estás diciendo cuál es en el comando?

2024-12-13 19:26 UTC, JJ commented on Dockerfile
> +ENV PYTHON_VERSION=3.12.0
¿Por qué descargas esta versión?

2024-12-13 19:26 UTC, JJ commented on docs/imagen_docker.md
> +La imagen de [Debian](https://hub.docker.com/_/debian) última imagen se hizo hace menos de una semana, por lo que tiene soporte activo. Pesa alrededor de 50MB, al igual que ubuntu, suelen ofrecer la
¿Seguro que no hay versiones más ligeras de Debian?

2024-12-13 19:26 UTC, JJ commented on docs/imagen_docker.md
> +* Debien "bookworm-slim": la imagen es mucho mas pequeña que bookworm normal, su peso en el disco es 52MB. No incluye funcionalidades más allá del sistema operativo básico y las dependencias mínimas
Pero eso es lo que quieres, ¿no?

2024-12-13 19:26 UTC, JJ commented on docs/imagen_docker.md
> +Usaremos la última versión estable de Alpine, que no cuenta con vulnerabilidades, un peso reducido, cuenta con mantenimiento en activo y sin funcionalidades extra.
¿Y una vez que estás instalando todo eso, sigue siendo la más ligera?

2024-12-13 19:26 UTC, JJ commented on docs/imagen_docker.md
> +La imagen de [bitnami/mindeb](https://hub.docker.com/r/bitnami/minideb) incluye muchos runtimes de lenguaje mantenidos por Bitnami, incluyendo PHP, Node.js, Ruby, y componentes de infraestructura com
¿Y para qué queremos todo eso?

2024-12-14 23:15 UTC, JLombar commented on Dockerfile
> +    shadow \
Pensaba que lo era para chmod y chown, pero es cierto que no es necesario. Borrada en [10b58b7](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/10b58b736efab33d46c3691d570dc2c223d1bab7)

2024-12-14 23:15 UTC, JLombar commented on Dockerfile
> +RUN curl -o /tmp/python.tar.xz https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz && \
No, no lo tuve en cuenta, lo uso en [3c9731f](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/3c9731f8142c42045f8e32bb5dece57db58db5dc)

2024-12-14 23:17 UTC, JLombar commented on Dockerfile
> +    rm -rf /usr/src/python /tmp/python.tar.xz
No, no estoy familiarizado con docker y nunca lo había escuchado, lo aplico en [9ff967f](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/9ff967fde4e7329ac22cfc76e6b303e1f8314061). También hablo sobre que añade en la conclusión de la elección de la imagen en [78e6bd7](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/78e6bd7c771a3a777aacfdbd437174172bf69418)

2024-12-14 23:18 UTC, JLombar commented on Dockerfile
> +ENTRYPOINT [ "make", "test" ]
Como le he comentado arriba, lo modifico en [9ff967f](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/9ff967fde4e7329ac22cfc76e6b303e1f8314061) para que los paquetes de coonstrucción de python no sean accesibles en la imagen final en [9ff967f](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/9ff967fde4e7329ac22cfc76e6b303e1f8314061)

2024-12-14 23:19 UTC, JLombar commented on Makefile
>  	@curl -LsSf https://astral.sh/uv/install.sh | sh
Modificado en [3c9731f](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/3c9731f8142c42045f8e32bb5dece57db58db5dc)

2024-12-14 23:21 UTC, JLombar commented on docs/imagen_docker.md
> +* Se tendrá en cuenta que la imagen pese poco, optimizando recursos al necesitar menos memoria y mayor velocidad de despliegue.
Como comento en la conclusión en [78e6bd7](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/78e6bd7c771a3a777aacfdbd437174172bf69418) la imagen es pesada, son 400MB más o menos, aún así he documentado por qué creo que hay motivos para que la imagen sea aceptable para este requisito a pesar de su gran peso comparado con el resto de las que se discuten en el documento

2024-12-14 23:22 UTC, JLombar commented on docs/imagen_docker.md
> +* No se piden funcionalidades extras al sólo ser usada para testear el proyecto
Con el uso de la construcción de la imagen en 2 fases [9ff967f](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/9ff967fde4e7329ac22cfc76e6b303e1f8314061) la imagen final no tiene funcionalidades extra.

2024-12-14 23:24 UTC, JLombar commented on Dockerfile
> +ENV PYTHON_VERSION=3.12.0
Modificado para que se use la última versión estable en [9c7d05b](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/9c7d05b964d85486192a663d8daf0218e16883db) y arreglado en [a752e9c](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/a752e9c535cabb06fea0b6490c02e4d1af935c12) ya que en dicho commit había un error

2024-12-14 23:24 UTC, JLombar commented on Dockerfile
> +RUN python3.12 --version
Eliminado en [9c7d05b](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/9c7d05b964d85486192a663d8daf0218e16883db)

2024-12-14 23:25 UTC, JLombar commented on docs/imagen_docker.md
> +La imagen de [Debian](https://hub.docker.com/_/debian) última imagen se hizo hace menos de una semana, por lo que tiene soporte activo. Pesa alrededor de 50MB, al igual que ubuntu, suelen ofrecer la
Las añado en [78e6bd7](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/78e6bd7c771a3a777aacfdbd437174172bf69418), pero como dice un en la siguiente línea las descarto al tener muchas vulnerabilidades

2024-12-14 23:26 UTC, JLombar commented on docs/imagen_docker.md
> +* Debien "bookworm-slim": la imagen es mucho mas pequeña que bookworm normal, su peso en el disco es 52MB. No incluye funcionalidades más allá del sistema operativo básico y las dependencias mínimas
Sí, sería la imagen perfecta, pero como dice un par de líneas más abajo la descarto por sus numerosas vulnerabilidades

2024-12-14 23:27 UTC, JLombar commented on docs/imagen_docker.md
> +Usaremos la última versión estable de Alpine, que no cuenta con vulnerabilidades, un peso reducido, cuenta con mantenimiento en activo y sin funcionalidades extra.
No, hablo de ello en [78e6bd7](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/78e6bd7c771a3a777aacfdbd437174172bf69418) como ya le he respondido en otro comentario

2024-12-14 23:28 UTC, JLombar commented on docs/imagen_docker.md
> +La imagen de [bitnami/mindeb](https://hub.docker.com/r/bitnami/minideb) incluye muchos runtimes de lenguaje mantenidos por Bitnami, incluyendo PHP, Node.js, Ruby, y componentes de infraestructura com
Realmente para nada. Lo listo para indicar que trae funcionalidades extra y luego comento que no la usaremos por ello, si es innecesario o redundante lo borraré

2024-12-14 23:28 UTC, JLombar commented
@JJ Listo para revisión

2024-12-15 10:53 UTC, JJ requested changes
Son pequeños detalles, pero tienen su importancia.

2024-12-15 10:53 UTC, JJ commented on .python-version
> +3.13.1
¿Esto para qué lo quieres? ¿No está en pyproject.toml?

2024-12-15 10:53 UTC, JJ commented on Dockerfile
> +    rm -rf /usr/src/python /tmp/python.tar.xz
En ese caso, es mejor que no sigas por este camino. Vas a tener una imagen con un montón de herramientas que no te sirven para nada. ¿No hay forma de descargarse el binario directamente? pyenv es lo que hace, ¿no?

2024-12-15 10:53 UTC, JJ commented on Dockerfile
> +ENV HOME=/home/userTest \
Esto no te va a servir de mucho, pero si lo defines, úsalo en las dos órdenes siguientes.

2024-12-15 10:53 UTC, JJ commented on Dockerfile
> +    make
¿De veras que necesitas poner esto en dos líneas ahora?

2024-12-15 10:53 UTC, JJ commented on Dockerfile
> +    chown -R userTest /home/userTest /app/test
Si acabas de crear esos directorios, ¿para qué quieres cambiar los usuarios?
¿No será más fácil que cambies al usuario no privilegiado después de  `adduser`?

2024-12-15 10:53 UTC, JJ commented on docs/imagen_docker.md
> +* No se piden funcionalidades extras al sólo ser usada para testear el proyecto
Esto debería de ser algo básico. quiero decir que no debería hacer falta ningún criterio. Además, está en el guión.

2024-12-15 10:53 UTC, JJ commented on pyproject.toml
> +requires-python = "==3.13.1"
Esto no creo que sea conveniente, sobre todo cuando vayamos al siguiente objetivo. ¿Por qué lo has cambiado?

2024-12-15 16:37 UTC, JJ requested changes
Porque si son versiones antiguas, no tienen los últimos cambios. Las imágenes "sin versión" se van actualizando siempre.

2024-12-15 16:37 UTC, JJ commented on Dockerfile
> +FROM python:3.13.1-alpine3.21
No hay *nunca* una buena razón para usar versiones específicas.

2024-12-15 17:48 UTC, JLombar commented on .python-version
> +3.13.1
Estaba desde el inicio y nunca me había parado a borralo, modificado en [dc77b4c](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/dc77b4c1e66a8039180a383f27874368b68a2dd0)

2024-12-15 17:48 UTC, JLombar commented on Dockerfile
> +ENV HOME=/home/userTest \
Cierto, eliminado en [a427266](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/a42726639f760f8b115355237fb1d49fc9c65288)

2024-12-15 17:49 UTC, JLombar commented on Dockerfile
> +    make
Eliminado en [a427266](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/a42726639f760f8b115355237fb1d49fc9c65288)

2024-12-15 17:49 UTC, JLombar commented on Dockerfile
> +    chown -R userTest /home/userTest /app/test
Como he modificado la imagen que se usa y el dockerfile no se corresponde con ningún commit el cambio

2024-12-15 17:50 UTC, JLombar commented on pyproject.toml
> +requires-python = "==3.13.1"
Ya que instalaba la última imagen estable de Python había pensado en modiifcarlo para que se correspondiera, en cualquier caso está borrado en [c3ee3ab](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/c3ee3ab67a00a5a5b21c483dba56290f4c9d412d)

2024-12-15 17:52 UTC, JLombar commented
@JJ Listo para revisión. La imagen no usa la etiqueta latest porque en dicho caso no instalaría la versión de alpine al no ser la última, a pesar de que se publicó hace 2 días

2024-12-15 18:55 UTC, JJ requested changes
Insisto, no hay *ninguna* buena razón para usar una versión del lenguaje en una imagen para test.

2024-12-15 18:55 UTC, JJ commented on Dockerfile
> +    chown userTest:userTest /app/test
Esto no tiene en realidad ningún efecto. Se va a montar de forma externa con los permisos que tenga el directorio externo.

2024-12-15 18:55 UTC, JJ commented on Dockerfile
> +FROM ghcr.io/astral-sh/uv:python3.13-alpine
Pensaba que con versión te referías a Alpine. Ya he dicho que no hay ninguna buena razón para usar una versión específica de un lenguaje. Pero me gustaría escuchar la tuya.

2024-12-16 19:04 UTC, JLombar commented on Dockerfile
> +    chown userTest:userTest /app/test
Modificado en [5bccdb9](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/5bccdb9d7f1b155965d0085aabfca8122a876c92)

2024-12-16 19:05 UTC, JLombar commented on Dockerfile
> +FROM ghcr.io/astral-sh/uv:python3.13-alpine
He añadido lo que hemos hablado por Telegram en [5c652b3](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/5c652b3e7ed36d297801698781ad533a94ed8bd8)

2024-12-16 19:05 UTC, JLombar commented
@JJ Listo para revisión

2024-12-16 19:35 UTC, JJ requested changes
Todavía debes pensar en dos o tres cosas para entender mejor como funcionan las imágenes docker.

2024-12-16 19:35 UTC, JJ commented on Dockerfile
> +COPY Makefile pyproject.toml uv.lock ./
¿En qué directorio está esto? ¿Qué pasa con ese directorio cuando se ejecuta de la forma indicada?
Por otro lado, ¿Dónde lo estás usando?

2024-12-16 19:35 UTC, JJ commented on Makefile
>  	uv run pytest
Si esto funciona sin que lo instales ¿para qué necesitas copiar pyproject.toml y más en un sitio que queda inaccesible?

2024-12-16 19:35 UTC, JJ commented on Dockerfile
> +ENTRYPOINT ["make", "test"]
¿Qué makefile estaría usando esto?

2024-12-16 19:49 UTC, JLombar commented on Dockerfile
> +COPY Makefile pyproject.toml uv.lock ./
Lo he modificado en [fc97a64](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/fc97a641e621800101f39f4506ffe18a531ceecc). El Makefile que se monta en la raíz del proyecto se asocia al directorio /app/test al usar el directorio actual como volumen, por lo que la copia era innecesaria

2024-12-16 20:13 UTC, JLombar commented on Makefile
>  	uv run pytest
Lo soluciono en [a229044](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/a229044ce59cc9632748dc2ef50485cf4c30affa)

2024-12-16 20:16 UTC, JLombar commented
@JJ Listo para revisión

2024-12-17 06:28 UTC, JJ requested changes
Si introduces código para resolver un error, ese error debe estar claramente explicado como un issue. Si no, es que simplemente te ha generado cosas ChatGPT y las has metido a jopo sin saber qué hacen ni por qué.

2024-12-17 06:28 UTC, JJ commented on Dockerfile
> +    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
Vamos a ver, Jorge. Si metes cosas súper rarunas como estas y además lo haces referenciando #23 que está relacionado con la imagen de docker, es que no estás entendiendo bien de qué va todo esto.

2024-12-17 07:36 UTC, JLombar commented
Buenos días Juan. No he usado ChatGPT ni nada por el estilo, he creado así la imagen de Docker por que así lo dice en la [documentación oficial de uv](https://docs.astral.sh/uv/guides/integration/docker/#installing-a-project) y el [ejemplo que se aporta en la misma](https://github.com/astral-sh/uv-docker-example/blob/main/Dockerfile), así que he intentado usarla.

He buscado qué hace la orden por no ponerla al azar y he entendido que, resumidamente, monta el archivo del host dentro del contenedor mientras ejecuta un comando durante la construcción de la imagen en Docker. No he visto problema con la orden y la he dejado. 

No sé qué error me menciona para el cuál debería crear un issue. Si se refiere a la correción que me puso en la última revisión, pues no había entendido hasta ahora en la que para error que se comete en las revisiones hay que crear un issue nuevo, y dudo mucho que sea eso lo que me está pidiendo.

Por otro lado, tengo que reconocer que este objetivo se habría beneficiado de la creación de más issues y eso he hecho.

En cualquier caso, @JJ listo para revisión

2024-12-17 07:47 UTC, JLombar commented
@JJ sí lo entiendo, pero también entiendo que la orden no hace eso, monta el archivo temporalmente durante la construcción del imagen, aunque luego no persista en la imagen final. Sin embargo esto último no tiene por qué ser un problema no?

2024-12-17 12:17 UTC, JJ commented
> @JJ sí lo entiendo, pero también entiendo que la orden no hace eso, monta el archivo temporalmente durante la construcción del imagen, aunque luego no persista en la imagen final. Sin embargo esto último no tiene por qué ser un problema no?

No lo sé. ¿Qué problema es realmente? Es decir, ¿qué resuelve? ¿Dónde está el issue que plantea el problema?

2024-12-17 12:18 UTC, JJ commented on Makefile
>  	uv run pytest
De veras que no sé qué es lo que soluciona eso ni si has entendido lo que te digo aquí.

2024-12-17 12:42 UTC, JLombar commented
@JJ El único problema que yo entiendo que hay relacionado con esto es que se necesita generar la imagen para poder testear la aplicación en un contenedor. Dicho problema es el issue #25, y el dockerfile resuelve este issue junto con el .dockerignore, los commits que crean dichos archivos están asociados al issue. No entiendo el por qué hacerlo de una forma determinada, en este caso usando
> RUN --mount=type=bind,source=uv.lock,target=uv.lock \
            --mount=type=bind,source=pyproject.toml,target=pyproject.toml \  

se tiene que crear un issue y asociarlo como si fuera un problema más que resolver. Se supone que tengo que crear un issue que sea "¿Se creará la imagen del docker siguiendo la documentación de la imagen base elegida?'" o "¿Se montarán los archivos durante la construcción de la imagen? No lo entiendo, no veo sentido alguno sinceramente.

No sé si es que no entiendo a lo que usted se refiere o qué es lo que pasa, pero por ejemplo si usara la orden COPY tendría que crear un nuevo issue que sea
>¿Cómo se copiaran los archivos del repositorio a la imagen de docker? 

o algo así. Realmente no comprendo que me está pidiendo

2024-12-17 13:15 UTC, JLombar commented
@JJ Esto es lo que que hace la construcción de la imagen.

1. Se define la imagen base a partir de la que se construye el contenedor. La misma ya trae instalado tanto python como uv en Alpine Linux
2. Se instala make sin almacenar los archivos temporales
3. Se establece /app/test como el directorio de trabajo, que es donde se montará el volumen asociado al repositorio local.
4. Se crea la carpeta que contendrá el entorno virtual y le da permisos de escritura recursivamente a todos los usuarios
5. Crea un usuario no privilegiado y le crea un directorio de inicio
6. Cambia al usuario nuevo
7. Crea la variable de entorno que uv usará para almacenar archivos de caché
8. Se montan los archivos locales uv.lock y pyproject.toml dentro del contenedor, dándole acceso al contenedor a estos archivos
9. Se sincronizan las dependencias de python basándose en "uv.lock", garantizando que no se modifiquen dependencias, instalándolas. Tiene también la opción de no instalar las dependencias que están en desarrollo. pyproject.toml se monta por que uv lo necesita para la instalación de dependencias.
10. Permite a cualquier usuario escribir en la cache
11. Ejecuta el entrypoint, en este caso make test que pasa los tests.

Con "docker run -u 1001 -t -v `pwd`:/app/test jlombar/horariosautomatricula:latest"  se descarga y se ejecuta un contenedor a partir de la imagen con el user id 1001, montando el directorio de mi ordenador, o el que sea que la esté ejecutando, en /app/test dentro del contenedor. Después se ejecuta el entrypoint definido en la imagen.

Si no he entendido algo o algo está mal digamelo y lo cambiaré. Hasta entonces no sé que es lo que espera que haga o qué es lo que hay que cambiar

2024-12-17 13:27 UTC, JJ commented
> @JJ Esto es lo que que hace la construcción de la imagen.
> 
>     1. Se define la imagen base a partir de la que se construye el contenedor. La misma ya trae instalado tanto python como uv en Alpine Linux
> 
>     2. Se instala make sin almacenar los archivos temporales
> 
>     3. Se establece /app/test como el directorio de trabajo, que es donde se montará el volumen asociado al repositorio local.
> 
>     4. Se crea la carpeta que contendrá el entorno virtual y le da permisos de escritura recursivamente a todos los usuarios
> 
>     5. Crea un usuario no privilegiado y le crea un directorio de inicio
> 
>     6. Cambia al usuario nuevo
> 
>     7. Crea la variable de entorno que uv usará para almacenar archivos de caché
> 
>     8. Se montan los archivos locales uv.lock y pyproject.toml dentro del contenedor, dándole acceso al contenedor a estos archivos
> 
1. Esos serían los archivos *en el momento de la construcción*
2. Si los necesitas, ¿para qué quieres montarlos? ¿Por qué no los copias simplemente?
3. ¿Qué problema resuelves con los archivos *dentro* de la imagen?

>     9. Se sincronizan las dependencias de python basándose en "uv.lock", garantizando que no se modifiquen dependencias, instalándolas. Tiene también la opción de no instalar las dependencias que están en desarrollo. pyproject.toml se monta por que uv lo necesita para la instalación de dependencias.

¿Qué dependencias? Si precisamente el comentario que te hice fue para que vieras que si eso funcionaba, no había ninguna dependencia. 

De veras que necesitáis poner el problema claramente en algún lado. Si no lo ponéis y lo expresáis claramente, no solamente no lo vais a resolver, es que vais a crear nuevos problemas o simplemente evidenciar que no estáis entendido lo que se hace.

> 
>     11. Ejecuta el entrypoint, en este caso make test que pasa los tests.

¿Ejecuta el entrypoint? ¿Cuando ejecuta el entrypoint?

> Si no he entendido algo o algo está mal digamelo y lo cambiaré. Hasta entonces no sé que es lo que espera que haga o qué es lo que hay que cambiar

No, lo que hay que cambiar lo tienes que decidir tú y quien tienes que entenderlo eres tú. Para empezar, ¿has entendido que no se debe añadir código si no tienes claramente qué problema resuelve ese código? ¿Y que si no lo haces así ni siquiera se puede ver si el código es correcto?

2024-12-17 20:02 UTC, JLombar commented
@JJ espero haber entendido el problema de una vez y que esté correcto, listo para revisión

2024-12-18 09:02 UTC, JJ requested changes
Seguimos con el mismo problema que ya te había señalado para otro fichero en otra ocasión.

2024-12-18 09:02 UTC, JJ commented on Dockerfile
> +ENV UV_CACHE_DIR=/home/userTest/.cache/uv
Estás haciendo esto antes de crear el directorio, pero bueno, no tiene mucha importancia.

2024-12-18 09:02 UTC, JJ commented on Dockerfile
> +RUN mkdir -p /app/test/.venv && \
Esto sí lo tiene. ¿Qué pasa con ese directorio cuando se monta el directorio externo? Si lo necesitas *durante* la construcción déjalo, si no por favor recuerda lo que ya te he dicho en otra ocasión.

2024-12-18 11:48 UTC, JLombar commented on Dockerfile
> +RUN mkdir -p /app/test/.venv && \
Es cierto, se me ha olvidado quitarlo junto con el resto de errores que cambié antes, no tiene sentido si quiera crearlo, no hace nada. Lo soluciono en [93d6e28](https://github.com/JLombar/HorariosAutomatricula/pull/24/commits/93d6e28ba0fd6b52350084369b43f5c5f195361b)

2024-12-18 11:48 UTC, JLombar commented
@JJ Listo para revisión

2024-12-19 11:26 UTC, JJ approved these changes
👍

2024-12-19 11:29 UTC, merged